More testing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,11 +10,10 @@ on:
 
 env:
   BUILD_TYPE: Release
-  CURRENT_MILESTONE: milestone2
-  TESTS_09_DIR: "${GITHUB_WORKSPACE}/Team09/Tests09/${CURRENT_MILESTONE}"
-  SOURCE_FILEPATH: ${TESTS_09_DIR}/${CURRENT_MILESTONE}_source_1.txt
-  QUERIES_FILEPATH: ${TESTS_09_DIR}/${CURRENT_MILESTONE}_queries_1.txt
-  OUT_FILEPATH: ${TESTS_09_DIR}/out.xml
+  TESTS_09_DIR: "${GITHUB_WORKSPACE}/Team09/Tests09/milestone2"
+  SOURCE_FILENAME: milestone2_source_1.txt
+  QUERIES_FILENAME: milestone2_queries_1.txt
+  OUT_FILENAME: out.xml
 
 jobs:
   build_windows:
@@ -41,9 +40,9 @@ jobs:
         shell: bash
         run: |
           cd Team09/Code09/build/src/autotester/Release
-          ./autotester.exe "${SOURCE_FILEPATH}" "${QUERIES_FILEPATH}" "${OUT_FILEPATH}"
-          passed_count=$(grep -c "<passed/>" "${OUT_FILEPATH}")
-          total_tests_count=$(grep -c "<id" "${OUT_FILEPATH}")
+          ./autotester.exe "${TESTS_09_DIR}/${SOURCE_FILENAME}" "${TESTS_09_DIR}/${QUERIES_FILENAME}" "${TESTS_09_DIR}/${OUT_FILENAME}"
+          passed_count=$(grep -c "<passed/>" "${TESTS_09_DIR}/${OUT_FILENAME}")
+          total_tests_count=$(grep -c "<id" "${TESTS_09_DIR}/${OUT_FILENAME}")
           echo "Passed: $passed_count / $total_tests_count"
 
           if [ $passed_count -ne $total_tests_count ]; then
@@ -53,7 +52,7 @@ jobs:
       
       - name: Output Autotester out.xml
         shell: bash
-        run: cat "${OUT_FILEPATH}"
+        run: cat "${TESTS_09_DIR}/${OUT_FILENAME}"
 
       - name: Unit Testing
         shell: bash
@@ -88,6 +87,24 @@ jobs:
         working-directory: ${{runner.workspace}}/build
         shell: bash
         run: cmake --build . --config $BUILD_TYPE
+
+      - name: Autotester System Testing
+        shell: bash
+        run: |
+          cd Team09/Code09/build/src/autotester/Release
+          ./autotester.exe "${TESTS_09_DIR}/${SOURCE_FILENAME}" "${TESTS_09_DIR}/${QUERIES_FILENAME}" "${TESTS_09_DIR}/${OUT_FILENAME}"
+          passed_count=$(grep -c "<passed/>" "${TESTS_09_DIR}/${OUT_FILENAME}")
+          total_tests_count=$(grep -c "<id" "${TESTS_09_DIR}/${OUT_FILENAME}")
+          echo "Passed: $passed_count / $total_tests_count"
+
+          if [ $passed_count -ne $total_tests_count ]; then
+            echo "Failed: $((total_tests_count - passed_count)) / $total_tests_count"
+            exit 1
+          fi
+      
+      - name: Output Autotester out.xml
+        shell: bash
+        run: cat "${TESTS_09_DIR}/${OUT_FILENAME}"
 
       - name: Run Unit Tests
         working-directory: ${{runner.workspace}}/build
